### ISSUE TITLE
redstone_mapper build error

### ISSUE THREAD

**Issue by cgarciae** [luizmineo/redstone.dart#71]
First time I build in a long time. I am getting this error:
```
C:\Users\Cristian Garcia\Documents\GitHub\aristadart>pub build
Loading source assets...
Loading redstone_mapper, di/module_transformer and smoke/src/default_transformer transformers...
Loading angular transformers...
Building aristadart...
Build error:
Transform StaticMapperGenerator on aristadart|web/main.dart threw error: The null object does not have a getter 'isDartCore'.

NoSuchMethodError: method not found: 'isDartCore'
Receiver: null
Arguments: []
dart:core-patch/object_patch.dart 45              Object.noSuchMethod
package:redstone_mapper/transformer.dart 508      _UsedLibs.resolveLib
package:redstone_mapper/transformer.dart 445      _TypeCodecGenerator._getTypeName
package:redstone_mapper/transformer.dart 479      _TypeCodecGenerator._buildMapper
package:redstone_mapper/transformer.dart 385      _TypeCodecGenerator._buildEncoder.<fn>
dart:collection/iterable.dart 227                 IterableBase.forEach
package:redstone_mapper/transformer.dart 381      _TypeCodecGenerator._buildEncoder
package:redstone_mapper/transformer.dart 367      _TypeCodecGenerator.toString
dart:core-patch/string_buffer_patch.dart 64       StringBuffer.write
dart:collection/maps.dart 302                     Maps.mapToString.<fn>
dart:collection-patch/collection_patch.dart 977   _HashMap&&_LinkedHashMapMixin.forEach
dart:collection/maps.dart 295                     Maps.mapToString
dart:collection-patch/collection_patch.dart 228   _HashMap.toString
package:redstone_mapper/transformer.dart 75       StaticMapperGenerator.applyResolver
package:code_transformers/src/resolvers.dart 113  Transformer&ResolverTransformer.applyToEntryPoints.<fn>.<fn>
dart:async/future.dart 118                        Future.Future.<fn>
dart:async-patch/timer_patch.dart 12              Timer._createTimer.<fn>
dart:io/timer_impl.dart 292                       _handleTimeout
dart:isolate-patch/isolate_patch.dart 130         _RawReceivePortImpl._handleMessage

dart:core                                         Object.noSuchMethod
package:redstone_mapper/transformer.dart 508      _UsedLibs.resolveLib
package:redstone_mapper/transformer.dart 445      _TypeCodecGenerator._getTypeName
package:redstone_mapper/transformer.dart 479      _TypeCodecGenerator._buildMapper
package:redstone_mapper/transformer.dart 385      _TypeCodecGenerator._buildEncoder.<fn>
dart:collection                                   IterableBase.forEach
package:redstone_mapper/transformer.dart 381      _TypeCodecGenerator._buildEncoder
package:redstone_mapper/transformer.dart 367      _TypeCodecGenerator.toString
dart:collection                                   _HashMap.toString
package:redstone_mapper/transformer.dart 75       StaticMapperGenerator.applyResolver
package:code_transformers/src/resolvers.dart 113  Transformer&ResolverTransformer.applyToEntryPoints.<fn>.<fn>
dart:isolate                                      _RawReceivePortImpl._handleMessage
Build failed.
```

**Comment by cgarciae** [comment]
Error appears to come from another source.

**Comment by cgarciae** [comment]
I am getting this with different settings. Sometimes build succeeds but I dont get `main.dart.js`.

**Comment by luizmineo** [comment]
Can you post your pubspec.yaml file?

**Comment by cgarciae** [comment]
```
name: aristadart
description: A sample web application
dependencies:
  angular: any
  async_await:
    git: https://github.com/dart-lang/async_await.git
  browser: any
  di: any
  fp: any
  http: any
  mongo_dart: any
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any
  shelf_static: any
dependency_overrides:
  analyzer: ^0.22.4
  barback: ^0.15.2+2
  code_transformers: ^0.2.3+2
  di: ^3.3.3
  route_hierarchical: ^0.6.1
transformers:
- async_await
- redstone_mapper
- angular:
    html_files:
    - lib/components/login/login.html
    - lib/components/login/nuevo_usuario.html
    - lib/components/home/home.html
    - lib/components/evento/evento.html
    - lib/components/vista/vista.html
```
